# Site
repository: mkyuhwan/mkyuhwan.github.io
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: 문규환
title: Engineer
# email:
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username: mkyuhwan
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: 문규환
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
#   - title: Blog
#     icon: fas fa-bookmark
#     url: https://mkyuhwan.github.io/blog
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url : Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/icon.png
about_content: | # this will include new lines to allow paragraphs
  단순한 기능 구현을 넘어, 복잡한 비즈니스 문제를 기술적으로 정의하고 해결하는 데 열정을 가지고 있습니다. <br/>
  
  비지니스 문제 도출 및 해결부터 자동화 및 모니터링까지 비지니스 전반에 걸친 해결책을 제공합니다. <br/>

  테스트를 통해 코드의 안정성을 높이고 지속적인 테스트 커버리지 관리를 중요하게 생각합니다. <br/>

  Milvus, Kafka 등 여러 인프라를 구축 및 운영하고, <br/>

  Scala, Thrift 등 다양한 기술들을 통해 비지니스 문제점을 해결하고 있습니다. <br/>
  
  새로운 기술 도입 등 다양한 방법으로 여러 문제들을 해결하는 것을 좋아합니다.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Ahnlab
        sub_title: Engineer
        caption: 2022.10 ~ Now
        link: https://www.ahnlab.com
        quote: >
          Artificial Intelligence Team
        description: |
          * LLM 기반 로그 진단 체계 구축
            * Kafka, Spark 를 활용한 대규모 데이터 처리 파이프라인 개발 및 운영
          * 통합 검색 서비스 개발
            * Milvus & LLM 기반 지식 검색 시스템 구축
          * Milvus, Kafka 등 인프라 구축 및 운영
            * Milvus 를 활용한 LLM 진단 체계 캐시 구성 (**QPS 200 이상 및 P99 100ms 이하**)
          * Docker & Kubernetes & Helm 기반 서비스 개발 및 운영
  - title: Project
    layout: list
    content:
      - layout: left
        title: IP 수집 및 진단 체계 구축
        caption: 2025.10 ~
        quote: >
          로그, MAIL 등 통합 도메인 진단을 위한 첫 걸음
        description: |
          * 주요 기술: Scala & Twitter Finatra, Python & Reflex, Thrift, Drools, Cassandra, Kubernetes
          * 주요 역할: 프론트, 백엔드 엔지니어
          * 담당 업무
            * IP 진단 체계 설계 및 개발
            * 파일, 로그 등 다양한 도메인에서 IP 추출 및 수집
          * 주요 성과
            * 파일, 로그 등 다양한 도메인을 연결지을 수 있는 도메인 -> 통합 진단 발판 마련
      - layout: left
        title: 통합 검색 서비스 개발
        caption: 2025.07 ~ 2025.12
        quote: >
          파편화된 여러 도메인의 시맨틱 통합 검색 엔진
        description: |
          * 주요 기술: Scala & Twitter Finatra, Http, Milvus, Cassandra, Kubernetes
          * 주요 역할: 백엔드, 인프라 엔지니어
          * 담당 업무
            * 파일, 로그 등 각 진단 도메인의 시맨틱 검색 기능 추가
            * cve, cwe 등 위협 인텔리전스 RAG 파이프라인 구축
          * 주요 성과
            * 풍부한 위협 인텔리전스 인사이트을 통한 보안 분석가의 탐지 및 대응 역량 강화
      - layout: left
        title: Milvus 인프라 설치 및 운영
        caption: 2025.07 ~ 2025.12
        quote: >
          팀 내 최다 트래픽 인프라 설치 및 운영
        description: |
          * 주요 기술: Scala & Twitter Finatra, Http, Milvus, Kubernetes
          * 주요 역할: 백엔드, 인프라 엔지니어
          * 담당 업무
            * Milvus 인프라 설치 및 운영
            * 임베딩 등 다양한 벡터 기반 솔루션 제공 REST API 서버 개발
          * 주요 성과
            * QPS 200 이상 및 P99 100ms 이하의 LLM 진단 체계 캐시를 통한 Coverage 100% 달성
            * 이미지 기반 URL 진단 체계에서 피싱 사이트 탐지 기능 추가
      - layout: left
        title: LLM 기반 로그 진단 체계 구축
        caption: 2024.10 ~ 2025.06
        quote: >
          LLM 기반 로그 위협 보고서 생성을 통한 업무 효율화
        description: |
          * 주요 기술: Scala & Twitter Finatra, Python & Reflex, Http, Mcp, Milvus, Kubernetes
          * 주요 역할: 백엔드 엔지니어
          * 담당 업무
            * LLM 기반 로그 진단 서비스 개발
          * 주요 성과
            * 기존 ML 모델 대비 진단 로그 범위 확장
            * AI 위협 보고서 생성을 통한 보안 관제 업무 효율화
      - layout: left
        title: AI API 개발
        caption: 2024.04 ~ 2024.09
        quote: >
          AI 진단 기능 등 여러 기능을 타팀에 제공하기 위한 REST API 서버 개발
        description: |
          * 주요 기술: Scala & Twitter Finatra, HTTP, Kubernetes
          * 주요 역할: 백엔드 엔지니어
          * 담당 업무
            * 팀내 Thrift 통신을 http 로 변환하여 타팀에 REST API 형태로 제공
            * 행위, 페이로드 도메인에 대한 API 개발
          * 주요 성과
            * 내부 API 표준화 및 인터페이스 제공
            * Twitter Finatra 를 통한 http 서버 개발 가이드 제공
            * 기존에 각 제품별 API 서버 통합을 통한 유지보수 비용 제거
            * Swagger 제공을 통한 타팀과의 의사소통 원활
      - layout: left
        title: AI Portal 개발
        caption: 2024.04 ~ 2024.09
        quote: >
          인공지능개발실이 제공하는 다양한 AI 진단 통합 포탈 서비스 개발
        description: |
          * 주요 기술: Python, Streamlit, Reflex, Spark, Postgres, Kubernetes
          * 주요 역할: 프론트, 데이터 엔지니어
          * 담당 업무
            * AI 수집량, AI 진단 미탐/오탐 등 다양한 통계 파이프라인 구축
            * 행위, 페이로드 도메인 AI Portal 개발
          * 주요 성과
            * AI 진단 결과에 대한 가시성 제공
            * 타팀에 AI 활용 가이드라인 제공
      - layout: left
        title: 실시간 로그 수집 및 진단 체계 구축
        caption: 2023.08 ~ 2024.03
        quote: >
          다양한 출처의 로그 데이터를 실시간으로 수집하고 진단하는 체계 구축
        description: |
          * 주요 기술: Scala, Twitter Finagle, Thrift, Airflow, Kafka, Spark, MinIO, Kubernetes
          * 주요 역할: 백엔드, 인프라 엔지니어
          * 담당 업무
            * Airflow 인프라 설치 및 운영
            * 다양한 형태의 로그 데이터를 수집 및 가공하여, ML 학습 데이터로 활용
            * 실시간 로그 수집 및 진단 체계 설계 및 개발
            * On-Premise 행위 로그 진단 서비스 개발
          * 주요 성과
            * 파일, 행위 등 다양한 도메인에서 활용 가능한 Kafka-Spark-MinIO 데이터 적재 파이프라인 구축
            * 사내 최초 로그 기반 ML 진단 서비스 제공
      - layout: left
        title: 빌드 머신 구축
        caption: 2023.06 ~ 2023.07
        quote: >
          폐쇄망 환경에서 인공지능팀의 공통된 빌드 환경 제공
        description: |
          * 주요 기술: CentOS7, RockyLinux, Jira
          * 주요 역할: 인프라 엔지니어
          * 담당 업무
            * 빌드 머신 구축 및 운영
            * CI/CD 환경 표준화 및 테스트 커버리지 관리
          * 주요 성과
            * 빌드 머신 구축 및 운영을 통한 안정적인 빌드 환경 제공
            * Java, Python 테스트 커버리지 추가 및 Jira 연동을 통한 관리
      - layout: left
        title: 파일 정적 분석 체계 구축
        caption: 2023.01 ~ 2023.05
        quote: >
          CAPA 등 다양한 정적 분석 도구를 통해 실시간으로 수집되는 파일들을 정적 분석하여, ML Feature 를 추출하는 체계 구축
        description: |
          * 주요 기술: Python, Celery-Flower, Kafka, MinIO, Kubernetes
          * 주요 역할: 백엔드, 인프라, 데이터 엔지니어
          * 담당 업무
            * Celery, Kafka 인프라 설치 및 운영
            * 파일 정적 분석 서비스 개발
            * 다양한 파일 정적 도구 추가
            * 각 정적 분석 도구의 ML Feature 성능 테스트
          * 주요 성과
            * 설명 가능한 모델 진단 결과 생성
            * 기존 ML 모델 성능이 낮아 진단할 수 없었던 .NET, ELF 등 진단 영역 확장
  - title: Technology
    layout: list
    content:
      - layout: left
        title: Frontend
        description: |
          * Python
            * Streamlit, Reflex (Tailwind CSS)
      - layout: left
        title: Backend
        description: |
          * Scala
            * Twitter Finatra, Twitter Server, Twitter Finagle
            * SBT
      - layout: left
        title: Data & AI Infrastructure
        description: |
          * Milvus, Cassandra, MinIO
          * Zookeeper, Kafka, Spark
          * Airflow
      - layout: left
        title: DevOps & Tool
        description: |
          * Grafana, Istio
          * Kubernetes, Helm, Rancher
          * VSCode, JetBrain Pycharm/IntelliJ
          * GitHub Copilot
  - title: Education
    layout: list
    content:
      - layout: left
        title: LLM Application with RAG
        caption: 2024.10 ~ 2024.10
        link: https://inf.run/j3KRb
        quote: >
          Vector Database Milvus Utilization
        description: |
          * LLM 진단 체계에서 Vector Database 활용 방안 탐색
          * LangChain 을 통한 RAG Application 개발
      - layout: left
        title: inflearn-sprig
        caption: 2022.04 ~ 2022.10
        link: https://www.inflearn.com/users/74366/@yh
        quote: >
          Java Spring Backend
        description: |
          * Spring Boot, MVC 등 Spring 기본 개념
          * Java JPA & Spring Data JPA, Querydsl 교육
      - layout: left
        title: 중앙대학교 컴퓨터공학부
        caption: 2015.03 ~ 2019.02
        link: https://www.cau.ac.kr

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
