# Site
repository: mkyuhwan/mkyuhwan.github.io
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: 문규환
title: Server Developer
# email:
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username: mkyuhwan
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: 문규환
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
  - title: Blog
    icon: fas fa-bookmark
    url: https://mkyuhwan.github.io/blog
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url : Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/icon.png
about_content: | # this will include new lines to allow paragraphs
  Kubernetes & Helm, Scala, Thrift 등 다양한 기술들을 통해 백엔드 서비스를 개발 및 운영하고 있습니다. <br/>

  테스트를 통해 코드의 안정성을 높이고 지속적인 테스트 커버리지 관리를 중요하게 생각합니다. <br/>

  Milvus, Kafka, 빌드 머신 (RockyLinux 8) 등 여러 인프라를 구축 및 운영하고 있습니다. <br/>

  새로운 기술 도입, 성능 튜닝 등 다양한 방법으로 여러 문제들을 해결하는 것을 좋아합니다.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Ahnlab
        sub_title: Server Developer
        caption: 2022.10 ~ Now
        link: https://www.ahnlab.com
        quote: >
          Artificial Intelligence Team
        description: |
          * 지식 검색 서비스 개발
            * 의미 검색을 통한 LLM 기반 RAG 구축
          * 행위, 페이로드 도메인 수집 및 진단 체계 구축
            * **일 500 만건** 행위 데이터 수집 및 악성 진단
          * Milvus, Kafka 등 인프라 구축 및 활용
            * Milvus 를 활용한 LLM 진단 체계 캐시 구성 (**QPS 200 이상 및 P99 100ms 이하**)
          * Docker & Kubernetes & Helm 기반 서비스 개발 및 운영
  - title: Technology
    layout: list
    content:
      - layout: left
        title: Frontend
        description: |
          * Streamlit (Python)
      - layout: left
        title: Backend
        description: | 
          * Scala
            * Twitter Finatra, Twitter Server, Twitter Finagle
            * SBT
      - layout: left
        title: DevOps
        description: |
          * HTTP, Apache Thrift
          * Cassandra, MinIO, Milvus
          * ZooKeeper, Kafka, Spark
          * Grafana, Istio
          * Kubernetes, Helm, Rancher
          * Git, Jira
      - layout: left
        title: Tool
        description: |
          * VSCode, JetBrain IntelliJ
          * GitHub Copilot
  - title: Education
    layout: list
    content:
      - layout: left
        title: LLM Application with RAG
        caption: 2024.10 ~ 2024.10
        link: https://inf.run/j3KRb
        quote: >
          Vector Database Milvus Utilization
        description: |
          * LLM 진단 체계에서 Vector Database 활용 방안 탐색
          * LangChain 을 통한 RAG Application 개발
      - layout: left
        title: inflearn-sprig
        caption: 2022.04 ~ 2022.10
        link: https://www.inflearn.com/users/74366/@yh
        quote: >
          Java Spring Backend
        description: |
          * Spring Boot, MVC 등 Spring 기본 개념
          * Java JPA & Spring Data JPA, Querydsl 교육
      - layout: left
        title: 중앙대학교 컴퓨터공학부
        caption: 2015.03 ~ 2019.02
        link: https://www.cau.ac.kr

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
